"""subjects

Revision ID: 0848502f09e6
Revises: 42fbcd576caa
Create Date: 2024-11-06 13:59:19.519535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0848502f09e6'
down_revision = '42fbcd576caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'department_id')
    # ### end Alembic commands ###
