"""ini

Revision ID: 0fab48a58439
Revises: e830150968a9
Create Date: 2024-10-02 17:39:44.540971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fab48a58439'
down_revision = 'e830150968a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id_instructor'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id_professor'], ),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_table('students',
    sa.Column('id_student', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('enroll_date', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id_group'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    op.add_column('subject', sa.Column('department_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'subject', 'department', ['department_name'], ['name'])
    op.drop_column('subject', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'department_name')
    op.drop_table('students')
    op.drop_table('groups')
    # ### end Alembic commands ###
