"""ini

Revision ID: 2903f8f617be
Revises: 0fab48a58439
Create Date: 2024-10-03 09:54:26.302525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2903f8f617be'
down_revision = '0fab48a58439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
