"""done

Revision ID: 2e06e87efc06
Revises: 719d159ff526
Create Date: 2024-10-03 10:15:21.063995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e06e87efc06'
down_revision = '719d159ff526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
