"""students

Revision ID: 32165251af9d
Revises: 0848502f09e6
Create Date: 2024-11-07 14:48:06.001808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32165251af9d'
down_revision = '0848502f09e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
