"""init

Revision ID: 448a231af8be
Revises: 
Create Date: 2024-09-26 11:35:11.522345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448a231af8be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('group',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('instructor',
    sa.Column('id_instructor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('employ_date', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_name'], ['department.name'], ),
    sa.PrimaryKeyConstraint('id_instructor')
    )
    op.create_table('professors',
    sa.Column('id_professor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department_name'], ['department.name'], ),
    sa.PrimaryKeyConstraint('id_professor')
    )
    op.create_index(op.f('ix_professors_name'), 'professors', ['name'], unique=False)
    op.create_table('student',
    sa.Column('id_student', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('enroll_date', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['group.name'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    op.create_table('subject',
    sa.Column('id_subject', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id_student'], ),
    sa.PrimaryKeyConstraint('id_subject')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('student')
    op.drop_index(op.f('ix_professors_name'), table_name='professors')
    op.drop_table('professors')
    op.drop_table('instructor')
    op.drop_table('group')
    op.drop_table('department')
    # ### end Alembic commands ###
