"""ini

Revision ID: 6c617dc859ec
Revises: 448a231af8be
Create Date: 2024-09-26 11:41:57.743386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c617dc859ec'
down_revision = '448a231af8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
