"""ini

Revision ID: b881e6e214b8
Revises: c2f12b0bde8c
Create Date: 2024-09-26 11:54:24.574065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b881e6e214b8'
down_revision = 'c2f12b0bde8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id_professor'], ),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_table('students',
    sa.Column('id_student', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('enroll_date', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id_group'], ),
    sa.PrimaryKeyConstraint('id_student')
    )
    op.drop_table('group')
    op.drop_table('student')
    op.drop_constraint('subject_student_id_fkey', 'subject', type_='foreignkey')
    op.create_foreign_key(None, 'subject', 'students', ['student_id'], ['id_student'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.create_foreign_key('subject_student_id_fkey', 'subject', 'student', ['student_id'], ['id_student'])
    op.create_table('student',
    sa.Column('id_student', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birth_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enroll_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photo', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['group.name'], name='student_group_name_fkey'),
    sa.PrimaryKeyConstraint('id_student', name='student_pkey')
    )
    op.create_table('group',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id_professor'], name='group_professor_id_fkey'),
    sa.PrimaryKeyConstraint('name', name='group_pkey')
    )
    op.drop_table('students')
    op.drop_table('groups')
    # ### end Alembic commands ###
