"""ini

Revision ID: 3af79bb4ddde
Revises: 9c6bbcef9f42
Create Date: 2024-09-26 11:47:05.436134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af79bb4ddde'
down_revision = '9c6bbcef9f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
