"""temp

Revision ID: 6b1fa7dbd387
Revises: 2e06e87efc06
Create Date: 2024-10-09 13:45:53.649904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1fa7dbd387'
down_revision = '2e06e87efc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('department_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'students', 'department', ['department_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'department_name')
    # ### end Alembic commands ###
