"""ini

Revision ID: 719d159ff526
Revises: 2903f8f617be
Create Date: 2024-10-03 10:13:07.355522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719d159ff526'
down_revision = '2903f8f617be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['students.id_student'], ),
    sa.ForeignKeyConstraint(['right_id'], ['subject.id_subject'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    # ### end Alembic commands ###
